set(_CATKIN_CURRENT_PACKAGE "zedroscenter")
set(zedroscenter_VERSION "0.0.0")
set(zedroscenter_MAINTAINER "user <user@todo.todo>")
set(zedroscenter_PACKAGE_FORMAT "2")
set(zedroscenter_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(zedroscenter_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(zedroscenter_BUILDTOOL_DEPENDS "catkin")
set(zedroscenter_BUILDTOOL_EXPORT_DEPENDS )
set(zedroscenter_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(zedroscenter_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(zedroscenter_TEST_DEPENDS )
set(zedroscenter_DOC_DEPENDS )
set(zedroscenter_URL_WEBSITE "")
set(zedroscenter_URL_BUGTRACKER "")
set(zedroscenter_URL_REPOSITORY "")
set(zedroscenter_DEPRECATED "")